/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package boaboa.org.butic.gui;

import boaboa.org.butic.model.Cliente;
import boaboa.org.butic.servicio.ServicioDB;
import boaboa.org.butic.utils.NumberUtils;
import boaboa.org.butic.utils.RutUtils;
import javax.swing.JOptionPane;

/**
 *
 * @author frubilar
 */
public class ClienteForm extends javax.swing.JFrame {

    /**
     * Creates new form ClienteForm
     */
    public ClienteForm() {
        initComponents();
    }
    private boolean update = false;
    private Integer id = null;

    ClienteForm(Cliente cliente) {
        initComponents();
        this.update = true;
        this.id = cliente.getId();
        this.nombreField.setText(cliente.getNombre());
        this.rutLabel.setText(cliente.getRut().toString());
        this.telefonoField.setText(cliente.getFono().toString());
        this.mailField.setText(cliente.getEmail());
        this.direccionField.setText(cliente.getDireccion());
    }

    ClienteForm(Integer rutString) {
        initComponents();
        this.rutLabel.setText(RutUtils.formatear(rutString));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        nombreField = new javax.swing.JTextField();
        telefonoField = new javax.swing.JTextField();
        mailField = new javax.swing.JTextField();
        direccionField = new javax.swing.JTextField();
        aceptarButton = new javax.swing.JButton();
        aceptarButton1 = new javax.swing.JButton();
        rutLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("CLIENTES");

        jLabel2.setText("Nombre Completo");

        jLabel3.setText("RUT");

        jLabel4.setText("Telefono");

        jLabel5.setText("E-mail");

        jLabel6.setText("Direccion");

        aceptarButton.setText("ATRAS");
        aceptarButton.setPreferredSize(new java.awt.Dimension(80, 40));
        aceptarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarButtonActionPerformed(evt);
            }
        });

        aceptarButton1.setText("GUARDAR");
        aceptarButton1.setPreferredSize(new java.awt.Dimension(80, 40));
        aceptarButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aceptarButton1ActionPerformed(evt);
            }
        });

        rutLabel.setText("RUT");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(aceptarButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(aceptarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addComponent(jLabel1)
                        .addGap(0, 291, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(direccionField)
                            .addComponent(mailField)
                            .addComponent(telefonoField)
                            .addComponent(nombreField)
                            .addComponent(rutLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(rutLabel))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(telefonoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(mailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(direccionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aceptarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(aceptarButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aceptarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarButtonActionPerformed

        MenuPrinipal menuPrinipal = new MenuPrinipal();
        menuPrinipal.setVisible(true);
        menuPrinipal.setLocationRelativeTo(null);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_aceptarButtonActionPerformed

    private void aceptarButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aceptarButton1ActionPerformed

        Cliente cliente = new Cliente();
        String nombre = this.nombreField.getText();
        String rut = this.rutLabel.getText();
        String fono = this.telefonoField.getText();
        String mail = this.mailField.getText();
        String direccion = this.direccionField.getText();

        if (nombre.length() * rut.length() * fono.length() * mail.length() * direccion.length() == 0) {
            JOptionPane.showMessageDialog(rootPane, "Existe un campo en blanco");
        } else {
            boolean ruth = RutUtils.isRut(rut);
            Integer fon = NumberUtils.NumberUtils(fono);
            if (fon == null) {
                JOptionPane.showMessageDialog(rootPane, "NO es numero ");
            } else {
                if (!ruth) {
                    JOptionPane.showMessageDialog(rootPane, "Por favor revise que el rut ingresado este bien");
                } else {
                    if (update == false) {
                        ServicioDB servicioDB = new ServicioDB();
                        Cliente preguntaCliente = new Cliente();
                        preguntaCliente = servicioDB.getClientePorRut(RutUtils.parseRut(rut));
                        if (preguntaCliente == null) {
                            cliente.setDireccion(direccion);
                            cliente.setEmail(mail);
                            cliente.setFono(fon);
                            cliente.setNombre(nombre);
                            cliente.setRut(RutUtils.parseRut(rut));
                            boolean salida = servicioDB.guardar(cliente);
                            if (salida) {
                                JOptionPane.showMessageDialog(rootPane, "Cliente Guardado exitosamente");
                                MenuPrinipal menuPrinipal = new MenuPrinipal();
                                menuPrinipal.setVisible(true);
                                menuPrinipal.setLocationRelativeTo(null);
                                this.dispose();
                            } else {
                                JOptionPane.showMessageDialog(rootPane, "hubo un error");
                            }
                        } else {
                            JOptionPane.showMessageDialog(rootPane, "Rut de cliente " + preguntaCliente.getNombre() + " ya fue ingresado previamente");
                        }
                    } else {
                        ServicioDB servicioDB = new ServicioDB();
                        cliente.setDireccion(direccion);
                        cliente.setEmail(mail);
                        cliente.setFono(fon);
                        cliente.setNombre(nombre);
                        cliente.setRut(RutUtils.parseRut(rut));
                        cliente.setId(id);
                        boolean salida = servicioDB.guardar(cliente);
                        if (salida) {
                            JOptionPane.showMessageDialog(rootPane, cliente.getNombre() + "Fue editado exitosamente");
                            MenuPrinipal menuPrinipal = new MenuPrinipal();
                            menuPrinipal.setVisible(true);
                            menuPrinipal.setLocationRelativeTo(null);
                            this.dispose();
                        } else {
                            JOptionPane.showMessageDialog(rootPane, "Error al ejecutar");
                        }
                    }
                }

            }
        }
    }//GEN-LAST:event_aceptarButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClienteForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClienteForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClienteForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClienteForm.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClienteForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton aceptarButton;
    private javax.swing.JButton aceptarButton1;
    private javax.swing.JTextField direccionField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField mailField;
    private javax.swing.JTextField nombreField;
    private javax.swing.JLabel rutLabel;
    private javax.swing.JTextField telefonoField;
    // End of variables declaration//GEN-END:variables
}
