/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package boaboa.org.butic.gui;

/**
 *
 * @author frubilar
 */
public class MenuPrinipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrinipal
     */
    public MenuPrinipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        clienteMenu = new javax.swing.JMenu();
        agregarMenu = new javax.swing.JMenu();
        modificaMenu = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        productosMenu = new javax.swing.JMenu();
        agregarProductosMenu = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        clienteMenu.setText("Clientes");
        clienteMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteMenuActionPerformed(evt);
            }
        });
        clienteMenu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                clienteMenuKeyPressed(evt);
            }
        });

        agregarMenu.setText("Agregar");
        agregarMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                agregarMenuMouseClicked(evt);
            }
        });
        agregarMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarMenuActionPerformed(evt);
            }
        });
        clienteMenu.add(agregarMenu);

        modificaMenu.setText("Modificar");
        modificaMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                modificaMenuMouseClicked(evt);
            }
        });
        modificaMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificaMenuActionPerformed(evt);
            }
        });
        clienteMenu.add(modificaMenu);

        jMenu6.setText("Buscar");
        clienteMenu.add(jMenu6);

        jMenuBar1.add(clienteMenu);

        productosMenu.setText("Prodcutos");

        agregarProductosMenu.setText("Agregar");
        productosMenu.add(agregarProductosMenu);

        jMenuBar1.add(productosMenu);

        jMenu3.setText("Edit");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 375, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarMenuActionPerformed
        ClienteForm form = new ClienteForm();
        form.setVisible(true);
        form.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_agregarMenuActionPerformed

    private void clienteMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteMenuActionPerformed

    }//GEN-LAST:event_clienteMenuActionPerformed

    private void clienteMenuKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_clienteMenuKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_clienteMenuKeyPressed

    private void modificaMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificaMenuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modificaMenuActionPerformed

    private void modificaMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_modificaMenuMouseClicked
        BuscarClienteParaEditar editar = new BuscarClienteParaEditar();
        editar.setVisible(true);
        editar.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_modificaMenuMouseClicked

    private void agregarMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_agregarMenuMouseClicked
        ClienteForm form = new ClienteForm();
        form.setVisible(true);
        form.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_agregarMenuMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrinipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrinipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrinipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrinipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrinipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu agregarMenu;
    private javax.swing.JMenu agregarProductosMenu;
    private javax.swing.JMenu clienteMenu;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu modificaMenu;
    private javax.swing.JMenu productosMenu;
    // End of variables declaration//GEN-END:variables
}
